### ISSUE TITLE
Make SecurityTests' timeout configurable

### ISSUE THREAD

**Issue by rafaveira3** [globocom/huskyCI#509]
<a href="https://opensource.globo.com/hacktoberfest/"><img align="right" src="https://user-images.githubusercontent.com/8943477/94613618-36e2d380-027b-11eb-8566-f8aa35ac792d.png" width="300"/></a>

## Motivation

We received [this feedback](https://github.com/globocom/huskyCI/issues/407) from huskyCI users (thanks, @igorfernandes 😃) that suggests that the analysis could have a timeout configurable. Some repositories that are "very large" take too long to finish, which impacts their CI somehow.

## It would be great if

We add new logic to let developers set this on their side, and not from the hardcoded the API [`config.yaml`](https://github.com/globocom/huskyCI/blob/master/api/config.yaml).

## What we expect

There are a few ways we can take this issue and a start suggestion is to add a new environment variable to the client code, as exemplified bellow:

```yaml
stages:
    - huskyCI

huskyCI:
    stage: huskyCI
    variables:
        HUSKYCI_CLIENT_TESTS_TIMEOUT: 360
    script:
        - wget $HUSKYCI_CLIENT_URL/huskyci-client
        - chmod +x huskyci-client
        - ./huskyci-client
```

## Tips

* [This is where the env vars are used by the client](https://github.com/globocom/huskyCI/blob/master/client/config/config.go#L28)
* [This is where the request comes to the API](https://github.com/globocom/huskyCI/blob/master/api/routes/analysis.go#L71)
