### ISSUE TITLE
Add support for accessing internal repositories with tokens

### ISSUE THREAD

**Issue by szymonwyrwiak** [globocom/huskyCI#519]
## Motivation
In our current setup, we are using SaaS Gitlab where all projects are private. In that case, huskyCI is always accessing internal repositories. [A current approach](https://huskyci.opensource.globo.com/docs/guides/accessing-internal-repositories) where SSH key is used is not the preferred option. 
We will have a lot of different teams to add their SSH keys and we don't have service users. It's hard to manage personal keys without service users for more than 500 repositories so we prefer access through tokens with a set expiration date.

## It would be great if
We add support for accessing internal repositories through tokens like:
* [Gitlab Project Access Tokens](https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html)
* [Gitlab Deploy Tokens](https://docs.gitlab.com/ee/user/project/deploy_tokens/)

Then we may add automation through [API](https://docs.gitlab.com/ee/api/deploy_tokens.html) and create tokens as needed.

## What we expect
We suggest adding a new environment variable that can be defined inside CI/CD
```yaml
huskyci-report:
  image: docker-registry/huskyci-client:<tag>
  variables:
    HUSKYCI_CLIENT_REPO_URL: <repo_url>
    HUSKYCI_CLIENT_REPO_BRANCH: <repo_name>
    HUSKYCI_CLIENT_API_ADDR: <huskyci_url>
    HUSKYCI_CLIENT_API_USE_HTTPS: "true"
    HUSKYCI_API_GIT_ACCESS_TOKEN: <git_access_token>
  script:
    - scan
```

## Tips
* [This is where we extracting variable GIT_SSH_URL](https://github.com/globocom/huskyCI/blob/master/api/util/util.go#L46)

**Comment by thepabloaguilar** [comment]
Is this issue already relevant to the project? Also, could you give more details about the automation part?

**Comment by szymonwyrwiak** [comment]
**thought:** Not sure if I'm the one that should answer these questions, but I will try. For me, this issue is still relevant.
Below I will assume that we are adding support for deploy token since it has the least amount of privileges. [Overview of GitLab tokens describes more options](https://docs.gitlab.com/ee/security/token_overview.html).
I did not check how it looks for GitHub or BitBucket, from a brief look, there are minor differences, so we may need an additional variable to identify the repository to support it properly. Below I will assume that we talk only about GitLab.

[util_test.go](https://github.com/globocom/huskyCI/blob/master/api/util/util_test.go) describes the flow, urrently when we want to check out the given repo to scan it. There are few steps.

1. We extract `%GIT_REPO%`, `%GIT_BRANCH%` from cmd and replace it with the proper repository `URL` in test it's seen as 
```
inputCMD := "git clone -b %GIT_BRANCH% --single-branch %GIT_REPO% code --quiet 2> /tmp/errorGitClone -- "

expected := "git clone -b myBranch --single-branch https://github.com/globocom/secDevLabs.git code --quiet 2> /tmp/errorGitClone -- "
```

2. Then we  extract `GIT_SSH_URL` and `GIT_URL_TO_SUBSTITUTE` from cmd and replace it with the `SSH` equivalent in test it looks like
```
expectedNotEmpty := "git config --global url.\"gitlab@gitlab.example.com:\".insteadOf \"https://gitlab.example.com/\""
```

3. It assumes that there is a PrivateSSHKey.

```
rawString := "echo '%GIT_PRIVATE_SSH_KEY%' > ~/.ssh/huskyci_id_rsa &&"
expectedNotEmpty := "echo 'PRIVKEYTEST' > ~/.ssh/huskyci_id_rsa &&"
```


**In case of support for GitLab tokens**

Instead of `HUSKYCI_API_GIT_PRIVATE_SSH_KEY` we will have the add `HUSKYCI_API_GIT_ACCESS_TOKEN` and add username `HUSKYCI_API_GIT_ACCESS_TOKEN_USERNAME`. It has few implications.

1. We check if we have both variables and decide flow when both variables are not empty. I'm leaning more towards token usage as a priority.

In case of `SSH` key flow we have 
```
cmd := util.HandleCmd(scanInfo.URL, scanInfo.Branch, scanInfo.Container.SecurityTest.Cmd)
cmd = util.HandleGitURLSubstitution(cmd)
finalCMD := util.HandlePrivateSSHKey(cmd)
```
For `TOKEN` flow we can have
```
cmd := util.HandleCmd(scanInfo.URL, scanInfo.Branch, scanInfo.Container.SecurityTest.Cmd)
cmd = util.HandleGitURLSubstitution(cmd)
finalCMD := util.HandlePrivateToken(cmd)
```
2. We can extend HandleGitURLSubstitution to support token based URL so to current transformation `https://gitlab.example.com/` to `gitlab@gitlab.example.com` 
add token specific from `https://gitlab.example.com` to `https://<username>:<deploy_token>@gitlab.example.com/` - this URL is simplified

3. In `HandlePrivateToken(cmd)` we will have to inject both OS variables `HUSKYCI_API_GIT_ACCESS_TOKEN`, `HUSKYCI_API_GIT_ACCESS_TOKEN_USERNAME` so we can clone the repository.

Variable names are added just as an example. I'm not sure how the current project naming convention looks. Also not included test specification in this answer. Please correct me if I get anything wrong.

**Comment by thepabloaguilar** [comment]
@szymonwyrwiak after some deep dive in the source code I just realized that you can do what you want without any modification!!
You can just use the "HUSKYCI_CLIENT_REPO_URL":
```yaml
huskyci-report:
  image: docker-registry/huskyci-client:<tag>
  variables:
    HUSKYCI_CLIENT_REPO_URL: https://<username>:<deploy_token>@gitlab.example.com/your_repository.git
    HUSKYCI_CLIENT_REPO_BRANCH: main
    HUSKYCI_CLIENT_API_ADDR: <huskyci_url>
    HUSKYCI_CLIENT_API_USE_HTTPS: "true"
  script:
    - scan
```

You can do something like:
```yaml
huskyci-report:
  image: docker-registry/huskyci-client:<tag>
  variables:
    HUSKYCI_CLIENT_REPO_BRANCH: main
    HUSKYCI_CLIENT_API_ADDR: <huskyci_url>
    HUSKYCI_CLIENT_API_USE_HTTPS: "true"
  script:
    - HUSKYCI_CLIENT_REPO_URL="$CI_SERVER_PROTOCOL://$CI_DEPLOY_USER:$CI_DEPLOY_PASSWORD@$CI_SERVER_URL/$CI_PROJECT_PATH.git"
    - scan
```

Of course, if you know which protocol to use and what's your instance URL you can make something shorter!
```text
https://$CI_DEPLOY_USER:$CI_DEPLOY_PASSWORD@gitlab.example.com/your_repository.git
```
> $CI_DEPLOY_USER and $CI_DEPLOY_PASSWORD exist if you set a project deploy token [Predefined variables reference](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html)

The reason I'm saying that solution works is because husky injects your repo url directly in the command, [example here](https://github.com/globocom/huskyCI/blob/master/api/config.yaml#L33), if you not set `HUSKYCI_API_GIT_SSH_URL` and `HUSKYCI_API_GIT_URL_TO_SUBSTITUTE` nothing will happen, as you can see [here](https://github.com/globocom/huskyCI/blob/master/api/util/util_test.go#L57). Also, if you not set `GIT_PRIVATE_SSH_KEY` nothing will happen too, see [here](https://github.com/globocom/huskyCI/blob/master/api/util/util_test.go#L101)!

Is that work for you?
